/*Data for OHPersonTranscript*/
// const OHPersonData = [
//     {
//       "id": 1,
//       "interview": [
//      {
//        "id": 1,
//        "speaker": "Interviewer",
//        "text": "Can you tell me a little bit about yourself?",
//        "cat": [],
//        "important": ""
//      },
//      {
//        "id": 1,
//        "speaker": "Claudine",
//        "text": "My name is Claudine Logan. My name is Logan-Clauzelle. I'm divorced. But, you know USCIS hasn't removed that yet so I still have to use it but. (mutual laughter) I love my Logan's so umm I use it for this or everything else that I'm in",
//        "cat": [1],
//        "important": ""
//      },
//      {
//        "id": 1,
//        "speaker": "",
//        "text": "I'm originally from Jamaica. Mother of four kids and I have two grandkids and I came here for the first time in 2005 as a hotel worker.",
//        "cat": [1,2,3],
//        "important": ""
//      },
//      {
//        "id": 1,
//        "speaker": "",
//        "text": "We used to come here like for seven to nine months at a time and go home back and forth every year until umm I stayed back in 2011  and I met and married my husband in 2012. So I met this man and within eleven days I got married.",
//        "cat": [1,3],
//        "important": ""
//      },
//      {
//        "id": 1,
//        "speaker": "",
//        "text": "Here I am. (mutual laughter). Seven years later. So you know I'm divorced but yeah I'm happy.",
//        "cat": [1,5],
//        "important": ""
//      },
//      {
//        "id": 1,
//        "speaker": "Interviewer",
//        "text": "Amazing. My mom met my dad. An American man, in, I don't even know what year she is. My mom left for me to go to Canada. Halfway through when she was in college because her sister got sponsored and like her sister allowed for her and my grandmother to come. And then my mom and my dad at church and everyone in my family was like: why are you marrying an American man? (mutual life) I don't know what you're doing. And she was like, \"No I'm in love like he's perfect\". Anyways they had two kids in Canada but they got a divorce. But she is happy as well. (Mutual laughter) You know it's..It's..It's a good it's a good thing.",
//        "cat": [],
//        "important": ""
//      },
//      {
//        "id": 1,
//        "speaker": "Claudine",
//        "text": "Mine is kind of typical in the opposite, because I wasn't even certain for where as I know when I came off the program.",
//        "cat": [],
//        "important": ""
//      },
//      {
//        "id": 1,
//        "speaker": "",
//        "text": "I still had time on my visa so I was like okay I'm going to try and see you what but if not I'm not gonna let my visa expire and go back.",
//        "cat": [3],
//        "important": ""
//      },
//      {
//        "id": 1,
//        "speaker": "",
//        "text": "But I was working at a casino and this man just like you know I ask him because I was a porter so I cleaned the machines and ashtrays and stuff. So I was like. Excuse me I'd like to clean the ashtray or whatever. And he turned around and was like \"Oh my God the Lord is sending my queen.\" (Laughter) So I'm like, you are crazy I don't even know you.",
//        "cat": [2],
//        "important": ""
//      },
//      {
//        "id": 1,
//        "speaker": "",
//        "text": "I lied to him a little because he wanted my phone number, I told him I didn't have a phone (laughter).",
//        "cat": [],
//        "important": ""
//      },
//      {
//        "id": 1,
//        "speaker": "",
//        "text": "I still had time on my visa so I was like okay I'm going to try and see you what but if not I'm not gonna let my visa expire and go back.",
//        "cat": [],
//        "important": 1
//      },
//      {
//        "id": 1,
//        "speaker": "Interviewer",
//        "text": "Here we are wow. Ok. OK. Umm, next question (mutual laughter). What are some of your long term plans and dreams or goals?",
//        "cat": [],
//        "important": ""
//      }]},
//      {
//      "id": 2,
//      "interview": [
//     {
//       "id": 2,
//       "speaker": "Interviewer",
//       "text": "Can you tell me a little bit about yourself?",
//       "cat": [],
//       "important": ""
//     },
//     {
//       "id": 2,
//       "speaker": "Claudine",
//       "text": "My name is Claudine Logan. My name is Logan-Clauzelle. I'm divorced. But, you know USCIS hasn't removed that yet so I still have to use it but. (mutual laughter) I love my Logan's so umm I use it for this or everything else that I'm in",
//       "cat": [1],
//       "important": ""
//     },
//     {
//       "id": 2,
//       "speaker": "",
//       "text": "I'm originally from Jamaica. Mother of four kids and I have two grandkids and I came here for the first time in 2005 as a hotel worker.",
//       "cat": [1,2,3],
//       "important": ""
//     },
//     {
//       "id": 2,
//       "speaker": "",
//       "text": "We used to come here like for seven to nine months at a time and go home back and forth every year until umm I stayed back in 2011  and I met and married my husband in 2012. So I met this man and within eleven days I got married.",
//       "cat": [1,3],
//       "important": ""
//     },
//     {
//       "id": 2,
//       "speaker": "",
//       "text": "Here I am. (mutual laughter). Seven years later. So you know I'm divorced but yeah I'm happy.",
//       "cat": [1,5],
//       "important": ""
//     },
//     {
//       "id": 2,
//       "speaker": "Interviewer",
//       "text": "Amazing. My mom met my dad. An American man, in, I don't even know what year she is. My mom left for me to go to Canada. Halfway through when she was in college because her sister got sponsored and like her sister allowed for her and my grandmother to come. And then my mom and my dad at church and everyone in my family was like: why are you marrying an American man? (mutual life) I don't know what you're doing. And she was like, \"No I'm in love like he's perfect\". Anyways they had two kids in Canada but they got a divorce. But she is happy as well. (Mutual laughter) You know it's..It's..It's a good it's a good thing.",
//       "cat": [],
//       "important": ""
//     },
//     {
//       "id": 2,
//       "speaker": "Claudine",
//       "text": "Mine is kind of typical in the opposite, because I wasn't even certain for where as I know when I came off the program.",
//       "cat":[],
//       "important": ""
//     },
//     {
//       "id": 2,
//       "speaker": "",
//       "text": "I still had time on my visa so I was like okay I'm going to try and see you what but if not I'm not gonna let my visa expire and go back.",
//       "cat": [3],
//       "important": ""
//     },
//     {
//       "id": 2,
//       "speaker": "",
//       "text": "But I was working at a casino and this man just like you know I ask him because I was a porter so I cleaned the machines and ashtrays and stuff. So I was like. Excuse me I'd like to clean the ashtray or whatever. And he turned around and was like \"Oh my God the Lord is sending my queen.\" (Laughter) So I'm like, you are crazy I don't even know you.",
//       "cat": [2],
//       "important": ""
//     },
//     {
//       "id": 2,
//       "speaker": "",
//       "text": "I lied to him a little because he wanted my phone number, I told him I didn't have a phone (laughter).",
//       "cat": [],
//       "important": ""
//     },
//     {
//       "id": 2,
//       "speaker": "",
//       "text": "I still had time on my visa so I was like okay I'm going to try and see you what but if not I'm not gonna let my visa expire and go back.",
//       "cat": [],
//       "important": 1
//     },
//     {
//       "id": 2,
//       "speaker": "Interviewer",
//       "text": "Here we are wow. Ok. OK. Umm, next question (mutual laughter). What are some of your long term plans and dreams or goals?",
//       "cat": [],
//       "important": ""
//     }]}
//   ]
  
//   export default OHPersonData